In [156]:
#cartesian coordinate
import numpy as np
import math
from sympy import *
np.set_printoptions(precision=16, suppress=True)


In [165]:
normal1 = np.array(
 [[3.95573,-2.28032,-2.59614],
[3.95587,2.28379,2.58154],
[-3.88E-03,-4.57E+00,2.60E+00]])

In [166]:
a1=normal1[0]
print(a1)

[ 3.95573 -2.28032 -2.59614]


In [159]:
basis1 = np.array(
    [[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [167]:
#求normal1的模长
data_M = np.sqrt(np.sum(normal1*normal1,axis=1))
a1_=data_M[0]
a1__=data_M[1]
a1___=data_M[2]
print(data_M)
print(a1_)
# norm_datam=a1/data_M
# print(norm_datam)

[5.252390125923625 5.246804074157906 5.257843194162413]
5.252390125923625


In [170]:
#对整个normal1进行正交化，并求出新的Z方向轴
nor_a1_=normal1[0]/a1_
nor_a1__=normal1[1]/a1__
#nor_a1___=normal1[2]/a1___
print(nor_a1_)
#print(nor_a1__)
#print(nor_a1___) #不需要这个
#验证x和y方向是不是单位向量
x=np.sqrt(np.sum(nor_a1_.dot(nor_a1_)))
y=np.sqrt(np.sum(nor_a1__.dot(nor_a1__)))
print(x)
print(y)
#在x基础上得到与x垂直的y向量
a2=nor_a1__-nor_a1_.dot(nor_a1__)/(nor_a1_.dot(nor_a1_))*nor_a1_
print(a2)
#得到新的z向量
z=np.cross(nor_a1_,a2)
print(z)
#计算z向量的模长和新的y向量的模长
z_z=np.sqrt(np.sum(z.dot(z)))
a2_a2=np.sqrt(np.sum(a2.dot(a2)))
#print(z_z)
#print(a2_a2)
#test验证是否xyz互相垂直
xy=nor_a1_.dot(a2)
xz=nor_a1_.dot(z)
yz=a2.dot(z)
print(xy)
print(xz)
print(yz)


[ 0.7531295096447906 -0.4341490150827303 -0.4942778311889908]
1.0
1.0
[0.6517887813654737 0.4941690653654088 0.5590749470278168]
[ 0.0015349762599486 -0.7432205859563885  0.6551467633520682]
5.551115123125783e-17
-5.551115123125783e-17
0.0


In [171]:
#以自己定的三个轴为新的坐标系basis2, 新的i,j,k
basis2=np.array([nor_a1_,a2,z])
print(basis2)

[[ 0.7531295096447906 -0.4341490150827303 -0.4942778311889908]
 [ 0.6517887813654737  0.4941690653654088  0.5590749470278168]
 [ 0.0015349762599486 -0.7432205859563885  0.6551467633520682]]


In [173]:
#将旋转矩阵进行单位化
A=basis2[0]/np.sqrt(np.sum(np.dot(basis2[0],basis2[0])))
B=basis2[1]/np.sqrt(np.sum(np.dot(basis2[1],basis2[1])))
C=basis2[2]/np.sqrt(np.sum(np.dot(basis2[2],basis2[2])))
print(A)
print(B)
print(C)
basis2_=np.array([A,B,C])
print(basis2_)


[ 0.7531295096447906 -0.4341490150827303 -0.4942778311889908]
[0.6578704594185799 0.4987800332821328 0.56429153548805  ]
[ 0.0015492987394067 -0.7501553913035417  0.6612597738949847]
[[ 0.7531295096447906 -0.4341490150827303 -0.4942778311889908]
 [ 0.6578704594185799  0.4987800332821328  0.56429153548805  ]
 [ 0.0015492987394067 -0.7501553913035417  0.6612597738949847]]


In [174]:
#RA=B
basis1_inver=np.linalg.inv(basis1)
print(basis1)
R=np.matmul(basis2_.T,basis1_inver)
print(R)
#Rzxy,Zphi,Ytheta,xposi,求出来的角度需要按XYZ轴开始绕
theta1=np.degrees(-np.arcsin(R[2,0]))
theta2=180-theta1
posi1=np.degrees(math.atan2(R[2,1]/np.cos(np.deg2rad(theta1)),R[2,2]/np.cos(np.deg2rad(theta1))))
posi2=np.degrees(math.atan2(R[2,1]/np.cos(np.deg2rad(theta2)),R[2,2]/np.cos(np.deg2rad(theta2))))
phi1=np.degrees(math.atan2(R[1,0]/np.cos(np.deg2rad(theta1)),R[0,0]/np.cos(np.deg2rad(theta1))))
phi2=np.degrees(math.atan2(R[1,0]/np.cos(np.deg2rad(theta2)),R[0,0]/np.cos(np.deg2rad(theta2))))
print('第1组绕ZYX角度为,phi1,theta1,posi1:',phi1,theta1,posi1)
print('第2组绕ZYX角度为,phi2,theta2,posi2:',phi2,theta2,posi2)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[ 0.7531295096447906  0.6578704594185799  0.0015492987394067]
 [-0.4341490150827303  0.4987800332821328 -0.7501553913035417]
 [-0.4942778311889908  0.56429153548805    0.6612597738949847]]
第1组绕ZYX角度为,phi1,theta1,posi1: -29.96172749288106 29.622140977282864 40.476060210072454
第2组绕ZYX角度为,phi2,theta2,posi2: 150.03827250711896 150.37785902271713 -139.52393978992754
